server:
  port: ${SERVER_PORT:8082}

spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
    pool:
      enabled: true
      initial-size: 1
      max-size: 5
      max-idle-time: 10m
      validation-query: SELECT 1
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

# Credenciales de APIs de Inteligencia Artificial
ai:
  imagga:
    url: https://api.imagga.com/v2/tags
    api-key: ${IMAGGA_API_KEY}
    api-secret: ${IMAGGA_API_SECRET}
  glm:
    url: https://openrouter.ai/api/v1/chat/completions
    api-key: ${OPENROUTER_API_KEY}
    model: z-ai/glm-4.5-air:free
