# kubectl apply -f luis-sanchez-37-secret-be.yml
apiVersion: v1
kind: Secret
metadata:
  name: luis-sanchez-37-secret-be
  namespace: luis-sanchez-37-namespace-be
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXNxbDovL2VwLXJvdWdoLWRyZWFtLWE1amd2MDF1LXBvb2xlci51cy1lYXN0LTIuYXdzLm5lb24udGVjaC9zcWw/c3NsbW9kZT1yZXF1aXJl   # en Base64
  DATABASE_USERNAME: ZGJfb3duZXI=   # en Base64
  DATABASE_PASSWORD: Q1R0cVhpNkcyTkZ4   # en Base64
  IMAGGA_API_KEY: YWNjXzMwYjE2MjBkOTU2YzlkNw==   # en Base64
  IMAGGA_API_SECRET: Y2Y3MjZiOGM4YmFmZGJkYTFjMjZmOTJmZDgzZTFlZmE=   # en Base64
  OPENROUTER_API_KEY: c2stb3ItdjEtMGZlOTQ1NGZjZGRhNWU3NzRhNTI2YmM3MDg1OGQyNTFiMTM2YWJhYjFiMzA0ZGU5NjFmYjA4ZDVhMjgwZTliYg==   # en Base64

# https://base64.guru/converter
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode
