# kubectl create namespace luis-sanchez-37-namespace-be (COMANDO)
# kubectl apply -f luis-sanchez-37-namespace-be.yml (yml)
apiVersion: v1
kind: Namespace
metadata:
  name: luis-sanchez-37-namespace-be
